// <auto-generated>
// This file was automatically generated from schemas/wire-schema.json.
// DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
// and run the schema generator to regenerate this file.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Selva.Schema.Models
{
// ============================================================================
    // TYPE ALIASES
    // ============================================================================

    // String-enum types are represented as 'string' in C# for compatibility
    // SolveEndedKind valid values: "ok", "blocked", "aborted", "error"

// ============================================================================
    // RUNTIME DATA
    // ============================================================================

    public class DiscoveredInput
    {

/// <summary>
/// Grasshopper parameter instance GUID
/// </summary>
        [JsonProperty("id")]
        [JsonConverter(typeof(TolerantGuidConverter))]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("default", NullValueHandling = NullValueHandling.Ignore)]
        public object Default { get; set; }

        [JsonProperty("minimum")]
        public double? Minimum { get; set; }

        [JsonProperty("maximum")]
        public double? Maximum { get; set; }

        [JsonProperty("stepSize")]
        public double? StepSize { get; set; }

        [JsonProperty("atLeast", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? AtLeast { get; set; } = 1;

        [JsonProperty("atMost", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? AtMost { get; set; } = 1;

        [JsonProperty("treeAccess", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public bool? TreeAccess { get; set; } = false;

/// <summary>
/// Key-value pairs for dropdown/selection options
/// </summary>
        [JsonProperty("options")]
        public Dictionary<string, object> Options { get; set; }

/// <summary>
/// File extensions the parameter accepts (e.g. ['.png', '.svg'] for an image input, geometry formats for a file input). Used to seed the file widget's accepted-formats default.
/// </summary>
        [JsonProperty("acceptedFormats")]
        public List<string> AcceptedFormats { get; set; } = new List<string>();

/// <summary>
/// Nickname of the directly enclosing Grasshopper group, if any. Used by the builder to offer 'Add by GH group' bulk import.
/// </summary>
        [JsonProperty("groupName")]
        public string GroupName { get; set; }
    }

    public class DiscoveredOutput
    {

/// <summary>
/// Grasshopper component instance GUID
/// </summary>
        [JsonProperty("id")]
        [JsonConverter(typeof(TolerantGuidConverter))]
        public Guid Id { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

/// <summary>
/// Output display type in UI: 'text' for text output, 'number' for numeric output, 'file' for downloadable files, 'chart' for rendered charts (e.g. Plotly), 'dynamicValueList' for computed value-list options routed back into a dynamic value list input
/// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

/// <summary>
/// For 'dynamicValueList' outputs: the instance GUID (paramId) of the DynamicValueList input that this output's computed options populate.
/// </summary>
        [JsonProperty("targetInputId", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(TolerantGuidConverter))]
        public Guid TargetInputId { get; set; }

/// <summary>
/// Nickname of the directly enclosing Grasshopper group, if any. Used by the builder to offer 'Add by GH group' bulk import.
/// </summary>
        [JsonProperty("groupName")]
        public string GroupName { get; set; }
    }

    public class SessionState
    {

        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("lastUpdate")]
        public DateTime LastUpdate { get; set; } = DateTime.UtcNow;

        [JsonProperty("mode")]
        public string Mode { get; set; }
    }

    public class RuntimeValues
    {

        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        [JsonProperty("values")]
        public Dictionary<string, object> Values { get; set; }
    }

    public class SolveEvent
    {

        [JsonProperty("solveId")]
        public string SolveId { get; set; }

/// <summary>
/// Per-solve, monotonic from 1. Lets a consumer drop late or duplicate delivery.
/// </summary>
        [JsonProperty("seq")]
        public int Seq { get; set; }

/// <summary>
/// ISO-8601 UTC timestamp
/// </summary>
        [JsonProperty("at")]
        public string At { get; set; }

/// <summary>
/// Event kind: solveStarted, solveEnded, diagnostic, progress, valueListUpdated, ...
/// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("payload")]
        public Dictionary<string, object> Payload { get; set; }
    }

    public class SolveDiagnostic
    {

        [JsonProperty("level")]
        public string Level { get; set; }

/// <summary>
/// What the author wrote, transport decoration stripped.
/// </summary>
        [JsonProperty("message")]
        public string Message { get; set; }

/// <summary>
/// Nickname of the component that raised it.
/// </summary>
        [JsonProperty("source")]
        public string Source { get; set; }

/// <summary>
/// Raised by a Selva Message component: the author chose to say this. Only these interrupt the user.
/// </summary>
        [JsonProperty("isGate")]
        public bool? IsGate { get; set; }
    }

    public class SolveOutcome
    {

        [JsonProperty("diagnostics")]
        public List<SolveDiagnostic> Diagnostics { get; set; } = new List<SolveDiagnostic>();

/// <summary>
/// A Message component raised an error, or the solve was aborted. The outputs are not a result.
/// </summary>
        [JsonProperty("blocked")]
        public bool Blocked { get; set; }

/// <summary>
/// The solve was stopped before it finished.
/// </summary>
        [JsonProperty("aborted")]
        public bool Aborted { get; set; }
    }

    public class SolveStartedPayload
    {
    }

    public class SolveEndedPayload
    {

        [JsonProperty("kind")]
        public string Kind { get; set; }
    }

    public class ProgressPayload
    {

/// <summary>
/// What is progressing; one bar per source.
/// </summary>
        [JsonProperty("source")]
        public string Source { get; set; }

/// <summary>
/// 0..1. Absent means indeterminate.
/// </summary>
        [JsonProperty("fraction")]
        public double? Fraction { get; set; }

        [JsonProperty("done")]
        public int? Done { get; set; }

        [JsonProperty("total")]
        public int? Total { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

/// <summary>
/// 0..1: where `fraction` will be when the running step ends. With `stepMs`, lets a host fill the bar across the step instead of jumping at its end.
/// </summary>
        [JsonProperty("nextFraction")]
        public double? NextFraction { get; set; }

/// <summary>
/// How long the running step took last time, in milliseconds. Absent before it has been timed.
/// </summary>
        [JsonProperty("stepMs")]
        public double? StepMs { get; set; }
    }

    public class ValidationIssueMessage
    {

        [JsonProperty("paramId")]
        public string ParamId { get; set; }

/// <summary>
/// warning = can still load, error = cannot load
/// </summary>
        [JsonProperty("severity")]
        public string Severity { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
        public object Details { get; set; }
    }

// ============================================================================
    // AVAILABLE PARAMETERS
    // ============================================================================

    public class DiscoveredParameters
    {

        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

/// <summary>
/// List of input parameters available for UI building
/// </summary>
        [JsonProperty("inputs")]
        public List<DiscoveredInput> Inputs { get; set; } = new List<DiscoveredInput>();

/// <summary>
/// List of output components available for UI building
/// </summary>
        [JsonProperty("outputs")]
        public List<DiscoveredOutput> Outputs { get; set; } = new List<DiscoveredOutput>();
    }

// ============================================================================
    // JSON CONVERTERS FOR DISCRIMINATED UNIONS
    // ============================================================================

}
