import type { InputParam } from '@computebuilder/core/grasshopper';

export const exampleInputTypes: InputParam[] = [
  {
    description: 'Basic number input',
    name: 'Radius',
    nickname: null,
    treeAccess: false,
    groupName: 'Geometry',
    paramType: 'Number',
    minimum: 1,
    maximum: 50,
    atLeast: 1,
    atMost: 1,
    stepSize: 0.5,
    default: 10,
  },
  {
    description: 'Height of the cylinder',
    name: 'Height',
    nickname: null,
    treeAccess: false,
    groupName: 'Geometry',
    paramType: 'Number',
    minimum: 1,
    maximum: 100,
    atLeast: 1,
    atMost: 1,
    stepSize: 1,
    default: 20,
  },
  {
    description: 'Number of segments',
    name: 'Segments',
    nickname: null,
    treeAccess: false,
    groupName: 'Settings',
    paramType: 'Integer',
    minimum: 3,
    maximum: 50,
    atLeast: 1,
    atMost: 1,
    stepSize: 1,
    default: 12,
  },
  {
    description: 'Material name',
    name: 'Material',
    nickname: null,
    treeAccess: false,
    groupName: 'Material',
    paramType: 'Text',
    default: 'Steel',
  },
  {
    description: 'Object name prefix',
    name: 'Prefix',
    nickname: null,
    treeAccess: false,
    groupName: 'Material',
    paramType: 'Text',
    default: 'Obj',
  },
  {
    description: 'Enable smoothing',
    name: 'Smooth',
    nickname: null,
    treeAccess: false,
    groupName: 'Settings',
    paramType: 'Boolean',
    default: true,
  },
  {
    description: 'Show wireframe',
    name: 'Wireframe',
    nickname: null,
    treeAccess: false,
    groupName: 'Display',
    paramType: 'Boolean',
    default: false,
  },
  {
    description: 'Rotation angle in degrees',
    name: 'Rotation',
    nickname: null,
    treeAccess: false,
    groupName: 'Transform',
    paramType: 'Number',
    minimum: 0,
    maximum: 360,
    atLeast: 1,
    atMost: 1,
    stepSize: 5,
    default: 0,
  },
  {
    description: 'Scale factor',
    name: 'Scale',
    nickname: null,
    treeAccess: false,
    groupName: 'Transform',
    paramType: 'Number',
    minimum: 0.1,
    maximum: 5.0,
    atLeast: 1,
    atMost: 1,
    stepSize: 0.1,
    default: 1.0,
  },
  {
    description: 'Center point X coordinate',
    name: 'Center X',
    nickname: null,
    treeAccess: false,
    groupName: 'Position',
    paramType: 'Number',
    minimum: -100,
    maximum: 100,
    atLeast: 1,
    atMost: 1,
    stepSize: 1,
    default: 0,
  },
  {
    description: 'Center point Y coordinate',
    name: 'Center Y',
    nickname: null,
    treeAccess: false,
    groupName: 'Position',
    paramType: 'Number',
    minimum: -100,
    maximum: 100,
    atLeast: 1,
    atMost: 1,
    stepSize: 1,
    default: 0,
  },
  {
    description: 'Center point Z coordinate',
    name: 'Center Z',
    nickname: null,
    treeAccess: false,
    groupName: 'Position',
    paramType: 'Number',
    minimum: -100,
    maximum: 100,
    atLeast: 1,
    atMost: 1,
    stepSize: 1,
    default: 0,
  },
  {
    description: 'Enable shadows',
    name: 'Cast Shadows',
    nickname: null,
    treeAccess: false,
    groupName: 'Display',
    paramType: 'Boolean',
    default: true,
  },
  {
    description: 'Transparency level',
    name: 'Opacity',
    nickname: null,
    treeAccess: false,
    groupName: 'Material',
    paramType: 'Number',
    minimum: 0,
    maximum: 1,
    atLeast: 1,
    atMost: 1,
    stepSize: 0.01,
    default: 1.0,
  },
  {
    description: 'This parameter is hidden from UI',
    name: 'Hidden Parameter',
    nickname: null,
    treeAccess: false,
    groupName: 'hidden',
    paramType: 'Number',
    minimum: 0,
    maximum: 100,
    atLeast: 1,
    atMost: 1,
    default: 50,
  },
];
