// <auto-generated>
// This file was automatically generated from schemas/ui-schema.json.
// DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
// and run the schema generator to regenerate this file.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Selva.Core.Models
{
// ============================================================================
    // CONSTANTS (from schema)
    // ============================================================================

    public static class AcceptedFileFormats
    {
        public static readonly string[] Values = new string[] { ".3dm", ".stp", ".step", ".fbx", ".obj", ".dxf", ".stl" };
    }

// ============================================================================
    // TYPE ALIASES
    // ============================================================================

    // String-enum types are represented as 'string' in C# for compatibility
    // GrasshopperParamType valid values: "number", "integer", "boolean", "text", "valueList", "file", "color", "generic"
    // GrasshopperInputStructure valid values: "item", "list", "tree"

// ============================================================================
    // UISchema
    // ============================================================================

    public class UISchema
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

/// <summary>
/// Grasshopper document file name (e.g., 'myfile.gh')
/// </summary>
        [JsonProperty("projectFileName")]
        public string ProjectFileName { get; set; }

/// <summary>
/// Grasshopper document unique identifier (GUID)
/// </summary>
        [JsonProperty("documentId", NullValueHandling = NullValueHandling.Ignore)]
        public Guid DocumentId { get; set; }

/// <summary>
/// Version of Selva plugin that created/last modified this schema
/// </summary>
        [JsonProperty("pluginVersion")]
        public string PluginVersion { get; set; }

/// <summary>
/// User-defined tags for organizing schemas (e.g., ['architecture', 'facade'])
/// </summary>
        [JsonProperty("tags")]
        public List<string> Tags { get; set; } = new List<string>();

/// <summary>
/// Category for organizing schemas (e.g., 'architecture', 'structural', 'mechanical')
/// </summary>
        [JsonProperty("category")]
        public string Category { get; set; }

/// <summary>
/// User or organization who created the schema
/// </summary>
        [JsonProperty("author")]
        public string Author { get; set; }

/// <summary>
/// Organization/company name
/// </summary>
        [JsonProperty("organization")]
        public string Organization { get; set; }

/// <summary>
/// Semantic version of the schema format (MAJOR.MINOR.PATCH)
/// </summary>
        [JsonProperty("schemaVersion", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string SchemaVersion { get; set; } = Constants.SchemaVersion.CURRENT_STRING;

/// <summary>
/// Minimum plugin version required to load this schema
/// </summary>
        [JsonProperty("minPluginVersion")]
        public string MinPluginVersion { get; set; }

        [JsonProperty("created", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime Created { get; set; } = DateTime.UtcNow;

/// <summary>
/// Last modification timestamp
/// </summary>
        [JsonProperty("lastModified", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime LastModified { get; set; } = DateTime.UtcNow;

/// <summary>
/// Configuration for the 3D viewer
/// </summary>
        [JsonProperty("viewerOptions", NullValueHandling = NullValueHandling.Ignore)]
        public ViewerOptions ViewerOptions { get; set; }

/// <summary>
/// If true, changes trigger immediate solving. If false, user must press Calculate button.
/// </summary>
        [JsonProperty("instanceSolve", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public bool? InstanceSolve { get; set; } = true;

        [JsonProperty("inputs")]
        public List<SchemaInput> Inputs { get; set; } = new List<SchemaInput>();

/// <summary>
/// All output components (print, bake, file download)
/// </summary>
        [JsonProperty("outputs")]
        public List<SchemaOutput> Outputs { get; set; } = new List<SchemaOutput>();

        [JsonProperty("layout")]
        public LayoutConfigBase Layout { get; set; }
    }

// ============================================================================
    // WIDGET CONFIGURATIONS
    // ============================================================================

    public class NumberWidgetConfig
    {

        [JsonProperty("minimum")]
        public double? Minimum { get; set; }

        [JsonProperty("maximum")]
        public double? Maximum { get; set; }

        [JsonProperty("stepSize")]
        public double? StepSize { get; set; }

        [JsonProperty("placeholder")]
        public string Placeholder { get; set; }

        [JsonProperty("renderAsSlider")]
        public bool? RenderAsSlider { get; set; }
    }

    public class TextWidgetConfig
    {

        [JsonProperty("placeholder")]
        public string Placeholder { get; set; }

        [JsonProperty("required")]
        public bool? Required { get; set; }

/// <summary>
/// Maximum character length for text input
/// </summary>
        [JsonProperty("maxLength")]
        public int? MaxLength { get; set; }

/// <summary>
/// Regex pattern for validation (e.g., email, phone)
/// </summary>
        [JsonProperty("pattern")]
        public string Pattern { get; set; }

/// <summary>
/// Custom error message shown when pattern validation fails
/// </summary>
        [JsonProperty("customErrorMessage")]
        public string CustomErrorMessage { get; set; }
    }

    public class DropdownWidgetConfig
    {

/// <summary>
/// Key-value pairs for dropdown options
/// </summary>
        [JsonProperty("options")]
        public Dictionary<string, object> Options { get; set; }

        [JsonProperty("required")]
        public bool? Required { get; set; }
    }

    public class CheckboxWidgetConfig
    {
    }

    public class FileWidgetConfig
    {

        [JsonProperty("buttonLabel", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string ButtonLabel { get; set; } = "Download";

/// <summary>
/// File format hint (e.g., '3dm') for setting download extension
/// </summary>
        [JsonProperty("fileFormat")]
        public string FileFormat { get; set; }
    }

    public class FileInputWidgetConfig
    {

/// <summary>
/// List of accepted file extensions (e.g., ['.3dm', '.step'])
/// </summary>
        [JsonProperty("acceptedFormats")]
        public List<string> AcceptedFormats { get; set; } = new List<string>();

/// <summary>
/// Which mode is active by default when both are allowed
/// </summary>
        [JsonProperty("defaultInputMode")]
        public string DefaultInputMode { get; set; }

/// <summary>
/// Which input modes the end user can choose from. If omitted, both are allowed.
/// </summary>
        [JsonProperty("allowedInputModes")]
        public List<string> AllowedInputModes { get; set; } = new List<string>();
    }

    public class ColorWidgetConfig
    {
    }

    public class ChartWidgetConfig
    {
    }

// ============================================================================
    // LAYOUT CONFIGURATION
    // ============================================================================

    public class GroupVisibilityCondition
    {

/// <summary>
/// Evaluation mode: 'all' = AND (all rules must pass), 'any' = OR (at least one rule must pass)
/// </summary>
        [JsonProperty("mode", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Mode { get; set; } = "all";

/// <summary>
/// List of rules to evaluate
/// </summary>
        [JsonProperty("rules")]
        public List<VisibilityRule> Rules { get; set; } = new List<VisibilityRule>();

/// <summary>
/// Action to apply when condition is met: 'show' makes group visible, 'hide' removes group from view
/// </summary>
        [JsonProperty("action", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Action { get; set; } = "show";
    }

    public class GroupConfig
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("order", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? Order { get; set; } = 0;

        [JsonProperty("collapsed", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public bool? Collapsed { get; set; } = false;

        [JsonProperty("columns", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? Columns { get; set; } = 1;

        [JsonProperty("items")]
        public List<LayoutItemBase> Items { get; set; } = new List<LayoutItemBase>();

        [JsonProperty("visibilityCondition", NullValueHandling = NullValueHandling.Ignore)]
        public GroupVisibilityCondition VisibilityCondition { get; set; }
    }

    public class TabConfig
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("icon")]
        public string Icon { get; set; }

        [JsonProperty("order", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? Order { get; set; } = 0;

        [JsonProperty("groups")]
        public List<GroupConfig> Groups { get; set; } = new List<GroupConfig>();

/// <summary>
/// Horizontal region where this tab should be positioned in multi-column layouts
/// </summary>
        [JsonProperty("position", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Position { get; set; } = "center";
    }

// ============================================================================
    // RUNTIME DATA
    // ============================================================================

    public class VisibilityRule
    {

/// <summary>
/// Parameter ID to watch for changes
/// </summary>
        [JsonProperty("paramId")]
        public string ParamId { get; set; }

/// <summary>
/// Comparison operator
/// </summary>
        [JsonProperty("operator")]
        public string Operator { get; set; }

/// <summary>
/// Value to compare against (used for equals, notEquals, greaterThan, lessThan, greaterThanOrEqual, lessThanOrEqual)
/// </summary>
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public object Value { get; set; }

/// <summary>
/// Array of values (used for 'in', 'notIn' operators, or [min, max] for 'between')
/// </summary>
        [JsonProperty("values")]
        public List<object> Values { get; set; } = new List<object>();
    }

    public class VisibilityCondition
    {

/// <summary>
/// Evaluation mode: 'all' = AND (all rules must pass), 'any' = OR (at least one rule must pass)
/// </summary>
        [JsonProperty("mode", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Mode { get; set; } = "all";

/// <summary>
/// List of rules to evaluate
/// </summary>
        [JsonProperty("rules")]
        public List<VisibilityRule> Rules { get; set; } = new List<VisibilityRule>();

/// <summary>
/// Action to apply when condition is met: 'show' makes visible and enabled, 'hide' removes from view, 'disable' makes visible but greyed out and non-interactive
/// </summary>
        [JsonProperty("action", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Action { get; set; } = "show";

/// <summary>
/// Default value to set for the parameter when condition is met. The value should be compatible with the parameter type (number, string, boolean, etc.)
/// </summary>
        [JsonProperty("defaultValue", NullValueHandling = NullValueHandling.Ignore)]
        public object DefaultValue { get; set; }
    }

    public class DiscoveredInput
    {

/// <summary>
/// Grasshopper parameter instance GUID
/// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("default", NullValueHandling = NullValueHandling.Ignore)]
        public object Default { get; set; }

        [JsonProperty("minimum")]
        public double? Minimum { get; set; }

        [JsonProperty("maximum")]
        public double? Maximum { get; set; }

        [JsonProperty("stepSize")]
        public double? StepSize { get; set; }

        [JsonProperty("atLeast", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? AtLeast { get; set; } = 1;

        [JsonProperty("atMost", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? AtMost { get; set; } = 1;

        [JsonProperty("treeAccess", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public bool? TreeAccess { get; set; } = false;

/// <summary>
/// Key-value pairs for dropdown/selection options
/// </summary>
        [JsonProperty("options")]
        public Dictionary<string, object> Options { get; set; }
    }

    public class DiscoveredOutput
    {

/// <summary>
/// Grasshopper component instance GUID
/// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

/// <summary>
/// Output display type in UI: 'text' for text/console output, 'number' for numeric output, 'file' for downloadable files, 'html' for rendered HTML (e.g. Plotly charts)
/// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public class SchemaInput
    {

/// <summary>
/// Grasshopper parameter instance GUID
/// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("paramType")]
        public string ParamType { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("default", NullValueHandling = NullValueHandling.Ignore)]
        public object Default { get; set; }

/// <summary>
/// Grasshopper data access mode: 'item' = Item Access, 'list' = List Access, 'tree' = Tree Access. Defaults to 'item'.
/// </summary>
        [JsonProperty("inputStructure", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string InputStructure { get; set; } = "item";
    }

    public class SchemaOutput
    {

/// <summary>
/// Grasshopper parameter instance GUID
/// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

/// <summary>
/// Output display type
/// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public class ViewerOptions
    {

/// <summary>
/// If true, display mesh data is sent to the web preview for local rendering
/// </summary>
        [JsonProperty("enableLocal", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public bool? EnableLocal { get; set; } = false;

/// <summary>
/// If true, enables remote rendering via Rhino Compute
/// </summary>
        [JsonProperty("enableRemote", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public bool? EnableRemote { get; set; } = false;

/// <summary>
/// Background color for the 3D viewer as hex string (e.g., '#ffffff')
/// </summary>
        [JsonProperty("backgroundColor", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string BackgroundColor { get; set; } = "#ffffff";
    }

    public class SessionState
    {

        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("lastUpdate")]
        public DateTime LastUpdate { get; set; } = DateTime.UtcNow;

        [JsonProperty("mode")]
        public string Mode { get; set; }
    }

    public class RuntimeValues
    {

        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        [JsonProperty("values")]
        public Dictionary<string, object> Values { get; set; }
    }

    public class ValidationIssueMessage
    {

        [JsonProperty("paramId")]
        public string ParamId { get; set; }

/// <summary>
/// warning = can still load, error = cannot load
/// </summary>
        [JsonProperty("severity")]
        public string Severity { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
        public object Details { get; set; }
    }

// ============================================================================
    // AVAILABLE PARAMETERS
    // ============================================================================

    public class DiscoveredParameters
    {

        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

/// <summary>
/// List of input parameters available for UI building
/// </summary>
        [JsonProperty("inputs")]
        public List<DiscoveredInput> Inputs { get; set; } = new List<DiscoveredInput>();

/// <summary>
/// List of output components available for UI building
/// </summary>
        [JsonProperty("outputs")]
        public List<DiscoveredOutput> Outputs { get; set; } = new List<DiscoveredOutput>();
    }

// ============================================================================
    // LAYOUTITEM (Discriminated Union)
    // ============================================================================

/// <summary>
    /// Base class for LayoutItem discriminated union
    /// </summary>
    [JsonConverter(typeof(LayoutItemBaseConverter))]
    public abstract class LayoutItemBase
    {
/// <summary>
/// Unique identifier for this layout item in the UI tree (not the parameter ID)
/// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

/// <summary>
/// References the Grasshopper component InstanceGuid (Data Source)
/// </summary>
        [JsonProperty("paramId")]
        public Guid ParamId { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("order", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? Order { get; set; } = 0;

        [JsonProperty("span", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? Span { get; set; } = 1;

/// <summary>
/// Base visibility (static). If false, item is always hidden regardless of conditions.
/// </summary>
        [JsonProperty("visible", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public bool? Visible { get; set; } = true;

        [JsonProperty("visibilityCondition", NullValueHandling = NullValueHandling.Ignore)]
        public VisibilityCondition VisibilityCondition { get; set; }

[JsonProperty("type")]
        public abstract string Type { get; }

[JsonProperty("widgetType")]
        public abstract string WidgetType { get; }

    }

public class InputNumberLayoutItem : LayoutItemBase
    {
public override string Type => "input";
public override string WidgetType => "number";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public NumberWidgetConfig Config { get; set; }
    }

public class InputTextLayoutItem : LayoutItemBase
    {
public override string Type => "input";
public override string WidgetType => "text";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public TextWidgetConfig Config { get; set; }
    }

public class InputDropdownLayoutItem : LayoutItemBase
    {
public override string Type => "input";
public override string WidgetType => "dropdown";

        [JsonProperty("config")]
        public DropdownWidgetConfig Config { get; set; }
    }

public class InputCheckboxLayoutItem : LayoutItemBase
    {
public override string Type => "input";
public override string WidgetType => "checkbox";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public CheckboxWidgetConfig Config { get; set; }
    }

public class InputFileLayoutItem : LayoutItemBase
    {
public override string Type => "input";
public override string WidgetType => "file";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public FileInputWidgetConfig Config { get; set; }
    }

public class InputColorLayoutItem : LayoutItemBase
    {
public override string Type => "input";
public override string WidgetType => "color";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public ColorWidgetConfig Config { get; set; }
    }

public class OutputTextLayoutItem : LayoutItemBase
    {
public override string Type => "output";
public override string WidgetType => "text";
    }

public class OutputNumberLayoutItem : LayoutItemBase
    {
public override string Type => "output";
public override string WidgetType => "number";
    }

public class OutputFileLayoutItem : LayoutItemBase
    {
public override string Type => "output";
public override string WidgetType => "file";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public FileWidgetConfig Config { get; set; }
    }

public class OutputChartLayoutItem : LayoutItemBase
    {
public override string Type => "output";
public override string WidgetType => "chart";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public ChartWidgetConfig Config { get; set; }
    }

// ============================================================================
    // LAYOUTCONFIG (Discriminated Union)
    // ============================================================================

/// <summary>
    /// Base class for LayoutConfig discriminated union
    /// </summary>
    [JsonConverter(typeof(LayoutConfigBaseConverter))]
    public abstract class LayoutConfigBase
    {
[JsonProperty("type")]
        public abstract string Type { get; }

        [JsonProperty("gap", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public int? Gap { get; set; } = 16;

    }

public class TabbedLayoutConfig : LayoutConfigBase
    {
public override string Type => "tabbed";

        [JsonProperty("tabs")]
        public List<TabConfig> Tabs { get; set; } = new List<TabConfig>();
    }

public class FlatLayoutConfig : LayoutConfigBase
    {
public override string Type => "flat";

        [JsonProperty("groups")]
        public List<GroupConfig> Groups { get; set; } = new List<GroupConfig>();
    }

// ============================================================================
    // JSON CONVERTERS FOR DISCRIMINATED UNIONS
    // ============================================================================


    /// <summary>
    /// JSON converter for LayoutItemBase discriminated union
    /// </summary>
    public class LayoutItemBaseConverter : JsonConverter<LayoutItemBase>
    {
        public override LayoutItemBase ReadJson(JsonReader reader, Type objectType, LayoutItemBase existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
var type = jsonObject["type"]?.Value<string>();
var widgetType = jsonObject["widgetType"]?.Value<string>();

            // Check if all discriminators are null or empty
            var allEmpty = string.IsNullOrEmpty(type) && string.IsNullOrEmpty(widgetType);
            if (allEmpty)
            {
                throw new JsonSerializationException($"LayoutItem discriminator fields are missing or empty. JSON: {jsonObject.ToString()}");
            }

            LayoutItemBase item;
            if (type == "input" && widgetType == "number")
                item = new InputNumberLayoutItem();
            else if (type == "input" && widgetType == "text")
                item = new InputTextLayoutItem();
            else if (type == "input" && widgetType == "dropdown")
                item = new InputDropdownLayoutItem();
            else if (type == "input" && widgetType == "checkbox")
                item = new InputCheckboxLayoutItem();
            else if (type == "input" && widgetType == "file")
                item = new InputFileLayoutItem();
            else if (type == "input" && widgetType == "color")
                item = new InputColorLayoutItem();
            else if (type == "output" && widgetType == "text")
                item = new OutputTextLayoutItem();
            else if (type == "output" && widgetType == "number")
                item = new OutputNumberLayoutItem();
            else if (type == "output" && widgetType == "file")
                item = new OutputFileLayoutItem();
            else if (type == "output" && widgetType == "chart")
                item = new OutputChartLayoutItem();
            else
                throw new JsonSerializationException($"Unknown LayoutItem variant: {type}/{widgetType}. JSON: {jsonObject.ToString()}");

            serializer.Populate(jsonObject.CreateReader(), item);
            return item;
        }

        public override void WriteJson(JsonWriter writer, LayoutItemBase value, JsonSerializer serializer)
        {
            // Serialize by writing properties directly to avoid converter recursion
            writer.WriteStartObject();

            // Use reflection to get all properties from the concrete type
            var properties = value.GetType().GetProperties();
            foreach (var property in properties)
            {
                var propValue = property.GetValue(value);

                // Skip null values if configured
                if (propValue == null && serializer.NullValueHandling == NullValueHandling.Ignore)
                    continue;

                // Get JsonProperty attribute - check property and base declaration
                var jsonAttr = property.GetCustomAttributes(typeof(JsonPropertyAttribute), true)
                    .FirstOrDefault() as JsonPropertyAttribute;

                // If not found and property is an override, check base class
                if (jsonAttr == null && property.GetGetMethod()?.GetBaseDefinition() != property.GetGetMethod())
                {
                    var baseProperty = property.DeclaringType?.BaseType?.GetProperty(property.Name);
                    if (baseProperty != null)
                    {
                        jsonAttr = baseProperty.GetCustomAttributes(typeof(JsonPropertyAttribute), true)
                            .FirstOrDefault() as JsonPropertyAttribute;
                    }
                }

                var jsonName = jsonAttr?.PropertyName ?? property.Name;

                writer.WritePropertyName(jsonName);
                serializer.Serialize(writer, propValue);
            }

            writer.WriteEndObject();
        }
    }


    /// <summary>
    /// JSON converter for LayoutConfigBase discriminated union
    /// </summary>
    public class LayoutConfigBaseConverter : JsonConverter<LayoutConfigBase>
    {
        public override LayoutConfigBase ReadJson(JsonReader reader, Type objectType, LayoutConfigBase existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
var type = jsonObject["type"]?.Value<string>();

            // Check if all discriminators are null or empty
            var allEmpty = string.IsNullOrEmpty(type);
            if (allEmpty)
            {
                throw new JsonSerializationException($"LayoutConfig discriminator fields are missing or empty. JSON: {jsonObject.ToString()}");
            }

            LayoutConfigBase item;
            if (type == "tabbed")
                item = new TabbedLayoutConfig();
            else if (type == "flat")
                item = new FlatLayoutConfig();
            else
                throw new JsonSerializationException($"Unknown LayoutConfig variant: {type}. JSON: {jsonObject.ToString()}");

            serializer.Populate(jsonObject.CreateReader(), item);
            return item;
        }

        public override void WriteJson(JsonWriter writer, LayoutConfigBase value, JsonSerializer serializer)
        {
            // Serialize by writing properties directly to avoid converter recursion
            writer.WriteStartObject();

            // Use reflection to get all properties from the concrete type
            var properties = value.GetType().GetProperties();
            foreach (var property in properties)
            {
                var propValue = property.GetValue(value);

                // Skip null values if configured
                if (propValue == null && serializer.NullValueHandling == NullValueHandling.Ignore)
                    continue;

                // Get JsonProperty attribute - check property and base declaration
                var jsonAttr = property.GetCustomAttributes(typeof(JsonPropertyAttribute), true)
                    .FirstOrDefault() as JsonPropertyAttribute;

                // If not found and property is an override, check base class
                if (jsonAttr == null && property.GetGetMethod()?.GetBaseDefinition() != property.GetGetMethod())
                {
                    var baseProperty = property.DeclaringType?.BaseType?.GetProperty(property.Name);
                    if (baseProperty != null)
                    {
                        jsonAttr = baseProperty.GetCustomAttributes(typeof(JsonPropertyAttribute), true)
                            .FirstOrDefault() as JsonPropertyAttribute;
                    }
                }

                var jsonName = jsonAttr?.PropertyName ?? property.Name;

                writer.WritePropertyName(jsonName);
                serializer.Serialize(writer, propValue);
            }

            writer.WriteEndObject();
        }
    }

}
