import type { InputParam } from '@selva/core';

export const exampleInputs: InputParam[] = [
  {
    name: 'Width',
    paramType: 'Number',
    description: 'Overall width in millimeters',
    default: 1200,
    minimum: 0,
    maximum: 5000,
    groupName: 'Geometry::Dimensions',
    id: 'geom-width',
    treeAccess: false,
    nickname: 'w',
  },
  {
    name: 'Height',
    paramType: 'Number',
    description: 'Overall height in millimeters',
    default: 800,
    minimum: 0,
    maximum: 4000,
    groupName: 'Geometry::Dimensions',
    id: 'geom-height',
    treeAccess: false,
    nickname: 'h',
  },
  {
    name: 'Depth',
    paramType: 'Number',
    description: 'Overall depth in millimeters',
    default: 300,
    minimum: 0,
    maximum: 2000,
    groupName: 'Geometry::Dimensions',
    id: 'geom-depth',
    treeAccess: false,
    nickname: 'd',
  },
  {
    name: 'Material',
    paramType: 'ValueList',
    description: 'Primary material',
    default: 'steel',
    groupName: 'Geometry::Specification',
    id: 'geom-material',
    treeAccess: false,
    nickname: 'mat',
    values: {
      steel: 'Steel',
      aluminum: 'Aluminum',
      plywood: 'Plywood',
      composite: 'Composite Panel',
    },
  },
  {
    name: 'Finish',
    paramType: 'ValueList',
    description: 'Surface finish type',
    default: 'matte-black',
    groupName: 'Geometry::Specification',
    id: 'geom-finish',
    treeAccess: false,
    nickname: 'finish',
    values: {
      'matte-black': 'Matte Black',
      'brushed-steel': 'Brushed Steel',
      'clear-coat': 'Clear Coat',
      'powder-white': 'Powder-Coated White',
    },
  },
  {
    name: 'Label',
    paramType: 'Text',
    description: 'Display label for UI and reports',
    default: 'Component A',
    groupName: 'Metadata::General',
    id: 'meta-label',
    treeAccess: false,
    nickname: 'lbl',
  },
  {
    name: 'Tag',
    paramType: 'Text',
    description: 'Short identifier for integration',
    default: 'CMP-A',
    groupName: 'Metadata::General',
    id: 'meta-tag',
    treeAccess: false,
    nickname: 'tag',
  },
  {
    name: 'IsActive',
    paramType: 'Boolean',
    description: 'Controls whether the component is processed',
    default: true,
    groupName: 'Metadata::Flags',
    id: 'meta-active',
    treeAccess: false,
    nickname: 'active',
  },
  {
    name: 'Tolerance',
    paramType: 'Number',
    description: 'Manufacturing tolerance in millimeters',
    default: 1,
    minimum: 0,
    maximum: 10,
    groupName: 'Manufacturing::Precision',
    id: 'mfg-tolerance',
    treeAccess: false,
    nickname: 'tol',
  },
  {
    name: 'ProductionMode',
    paramType: 'ValueList',
    description: 'Manufacturing workflow mode',
    default: 'prototype',
    groupName: 'Manufacturing::Workflow',
    id: 'mfg-mode',
    treeAccess: false,
    nickname: 'mode',
    values: {
      prototype: 'Prototype',
      batch: 'Batch Production',
      automated: 'Automated Line',
    },
  },
] as const;
