#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const schemaPath = path.join(__dirname, 'ui-schema.json');
const outputPath = path.join(__dirname, '../Plugin/Models/Generated/UISchema.Generated.cs');

const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
const definitions = schema.definitions;

// Type mappings from JSON Schema to C#
function jsonTypeToCSharp(prop, propName, required) {
  if (!prop) return 'object';

  if (prop.$ref) {
    const refName = prop.$ref.replace('#/definitions/', '');
    return refName;
  }

  if (prop.const) {
    return 'string';
  }

  if (prop.enum) {
    // Return string for inline enums, we'll handle GrasshopperParamType specially
    if (prop.description === 'Grasshopper parameter types') {
      return 'GrasshopperParamType';
    }
    return 'string';
  }

  switch (prop.type) {
    case 'string':
      if (prop.format === 'date-time') return 'DateTime';
      if (prop.format === 'uuid') return 'Guid';
      return 'string';
    case 'number':
      return required ? 'double' : 'double?';
    case 'integer':
      return required ? 'int' : 'int?';
    case 'boolean':
      return required ? 'bool' : 'bool?';
    case 'array':
      const itemType = jsonTypeToCSharp(prop.items, propName, true);
      return `List<${itemType}>`;
    case 'object':
      if (prop.additionalProperties) {
        return 'Dictionary<string, object>';
      }
      return 'object';
    default:
      return 'object';
  }
}

function pascalCase(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function camelCase(str) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

function generateProperty(name, prop, required) {
  const csharpType = jsonTypeToCSharp(prop, name, required);
  const pascalName = pascalCase(name);
  const nullHandling = !required && csharpType !== 'string' && !csharpType.endsWith('?') && !csharpType.startsWith('List') && !csharpType.startsWith('Dictionary')
    ? ', NullValueHandling = NullValueHandling.Ignore'
    : '';

  let defaultValue = '';
  if (prop.default !== undefined) {
    if (typeof prop.default === 'string') {
      defaultValue = ` = "${prop.default}";`;
    } else if (typeof prop.default === 'boolean') {
      defaultValue = ` = ${prop.default};`;
    } else if (typeof prop.default === 'number') {
      defaultValue = ` = ${prop.default};`;
    }
  } else if (csharpType.startsWith('List<')) {
    defaultValue = ` = new ${csharpType}();`;
  } else if (csharpType === 'DateTime') {
    defaultValue = ' = DateTime.UtcNow;';
  }

  const description = prop.description ? `\n        /// <summary>\n        /// ${prop.description}\n        /// </summary>` : '';

  return `${description}
        [JsonProperty("${name}"${nullHandling})]
        public ${csharpType} ${pascalName} { get; set; }${defaultValue}`;
}

function generateClass(name, def) {
  if (!def.properties) return '';

  const required = def.required || [];
  const props = Object.entries(def.properties)
    .filter(([propName]) => propName !== 'type' && propName !== 'widgetType') // Skip discriminator props for layout items
    .map(([propName, prop]) => generateProperty(propName, prop, required.includes(propName)))
    .join('\n');

  return `    public class ${name}
    {
${props}
    }`;
}

function generateLayoutItemClass(name, def) {
  const required = def.required || [];
  const typeValue = def.properties.type?.const || 'input';
  const widgetTypeValue = def.properties.widgetType?.const || 'text';

  const props = Object.entries(def.properties)
    .filter(([propName]) => propName !== 'type' && propName !== 'widgetType')
    .map(([propName, prop]) => generateProperty(propName, prop, required.includes(propName)))
    .join('\n');

  return `    public class ${name} : LayoutItemBase
    {
        public override string Type => "${typeValue}";
        public override string WidgetType => "${widgetTypeValue}";
${props}
    }`;
}

// Generate the C# file
let output = `// <auto-generated>
// This file was automatically generated from schemas/ui-schema.json.
// DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
// and run the schema generator to regenerate this file.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ComputeBuilder.Plugin.Models.Generated
{
    // ============================================================================
    // ENUMS
    // ============================================================================

    public enum GrasshopperParamType
    {
        Number,
        Integer,
        Boolean,
        Text,
        Generic
    }

    // ============================================================================
    // MAIN UI SCHEMA
    // ============================================================================

    public class UISchema
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; } = "1.0";

        [JsonProperty("created")]
        public DateTime Created { get; set; } = DateTime.UtcNow;

        [JsonProperty("inputs")]
        public List<InputParamSchema> Inputs { get; set; } = new List<InputParamSchema>();

        [JsonProperty("outputs")]
        public List<OutputParamSchema> Outputs { get; set; } = new List<OutputParamSchema>();

        [JsonProperty("layout")]
        public LayoutConfig Layout { get; set; } = new LayoutConfig();

        [JsonProperty("enable3dViewer")]
        public bool Enable3dViewer { get; set; }
    }

    // ============================================================================
    // PARAMETER SCHEMAS
    // ============================================================================

    public class InputParamSchema
    {
        /// <summary>
        /// Grasshopper parameter instance GUID
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("paramType")]
        public GrasshopperParamType ParamType { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("atLeast")]
        public int AtLeast { get; set; } = 1;

        [JsonProperty("atMost")]
        public int AtMost { get; set; } = int.MaxValue;

        [JsonProperty("treeAccess")]
        public bool TreeAccess { get; set; }

        [JsonProperty("default", NullValueHandling = NullValueHandling.Ignore)]
        public object Default { get; set; }

        [JsonProperty("minimum", NullValueHandling = NullValueHandling.Ignore)]
        public double? Minimum { get; set; }

        [JsonProperty("maximum", NullValueHandling = NullValueHandling.Ignore)]
        public double? Maximum { get; set; }

        [JsonProperty("stepSize", NullValueHandling = NullValueHandling.Ignore)]
        public double? StepSize { get; set; }
    }

    public class OutputParamSchema
    {
        /// <summary>
        /// Grasshopper parameter instance GUID
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("paramType")]
        public GrasshopperParamType ParamType { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }
    }

    // ============================================================================
    // WIDGET CONFIGURATIONS (Discriminated by widget type)
    // ============================================================================

    public class NumberWidgetConfig
    {
        [JsonProperty("min", NullValueHandling = NullValueHandling.Ignore)]
        public double? Min { get; set; }

        [JsonProperty("max", NullValueHandling = NullValueHandling.Ignore)]
        public double? Max { get; set; }

        [JsonProperty("step", NullValueHandling = NullValueHandling.Ignore)]
        public double? Step { get; set; }

        [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
        public string Placeholder { get; set; }

        [JsonProperty("renderAsSlider", NullValueHandling = NullValueHandling.Ignore)]
        public bool? RenderAsSlider { get; set; }
    }

    public class TextWidgetConfig
    {
        [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
        public string Placeholder { get; set; }

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Required { get; set; }
    }

    public class DropdownWidgetConfig
    {
        [JsonProperty("options")]
        public List<string> Options { get; set; } = new List<string>();

        [JsonProperty("required", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Required { get; set; }
    }

    public class CheckboxWidgetConfig
    {
    }

    // ============================================================================
    // LAYOUT ITEMS (Discriminated Union)
    // ============================================================================

    /// <summary>
    /// Base class for all layout items
    /// </summary>
    [JsonConverter(typeof(LayoutItemConverter))]
    public abstract class LayoutItemBase
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// References the Grasshopper component InstanceGuid
        /// </summary>
        [JsonProperty("paramId")]
        public Guid ParamId { get; set; }

        [JsonProperty("displayName", NullValueHandling = NullValueHandling.Ignore)]
        public string DisplayName { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("order")]
        public int Order { get; set; }

        [JsonProperty("span")]
        public int Span { get; set; } = 1;

        [JsonProperty("type")]
        public abstract string Type { get; }

        [JsonProperty("widgetType")]
        public abstract string WidgetType { get; }
    }

    // Input layout items
    public class InputNumberLayoutItem : LayoutItemBase
    {
        public override string Type => "input";
        public override string WidgetType => "number";

        [JsonProperty("config")]
        public NumberWidgetConfig Config { get; set; } = new NumberWidgetConfig();
    }

    public class InputTextLayoutItem : LayoutItemBase
    {
        public override string Type => "input";
        public override string WidgetType => "text";

        [JsonProperty("config")]
        public TextWidgetConfig Config { get; set; } = new TextWidgetConfig();
    }

    public class InputDropdownLayoutItem : LayoutItemBase
    {
        public override string Type => "input";
        public override string WidgetType => "dropdown";

        [JsonProperty("config")]
        public DropdownWidgetConfig Config { get; set; } = new DropdownWidgetConfig();
    }

    public class InputCheckboxLayoutItem : LayoutItemBase
    {
        public override string Type => "input";
        public override string WidgetType => "checkbox";

        [JsonProperty("config", NullValueHandling = NullValueHandling.Ignore)]
        public CheckboxWidgetConfig Config { get; set; }
    }

    // Output layout items
    public class OutputTextLayoutItem : LayoutItemBase
    {
        public override string Type => "output";
        public override string WidgetType => "text";
    }

    public class OutputNumberLayoutItem : LayoutItemBase
    {
        public override string Type => "output";
        public override string WidgetType => "number";
    }

    // ============================================================================
    // LAYOUT CONFIGURATION
    // ============================================================================

    public class GroupConfig
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("order")]
        public int Order { get; set; }

        [JsonProperty("collapsed")]
        public bool Collapsed { get; set; }

        [JsonProperty("columns")]
        public int Columns { get; set; } = 1;

        [JsonProperty("items")]
        public List<LayoutItemBase> Items { get; set; } = new List<LayoutItemBase>();
    }

    public class TabConfig
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public string Icon { get; set; }

        [JsonProperty("order")]
        public int Order { get; set; }

        [JsonProperty("groups")]
        public List<GroupConfig> Groups { get; set; } = new List<GroupConfig>();
    }

    public class LayoutConfig
    {
        [JsonProperty("type")]
        public string Type { get; set; } = "tabbed";

        [JsonProperty("gap")]
        public int Gap { get; set; } = 16;

        [JsonProperty("tabs", NullValueHandling = NullValueHandling.Ignore)]
        public List<TabConfig> Tabs { get; set; } = new List<TabConfig>();

        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public List<LayoutItemBase> Items { get; set; } = new List<LayoutItemBase>();
    }

    // ============================================================================
    // RUNTIME DATA
    // ============================================================================

    public class RuntimeValues
    {
        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        [JsonProperty("values")]
        public Dictionary<string, object> Values { get; set; } = new Dictionary<string, object>();
    }

    public class SessionState
    {
        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("lastUpdate")]
        public DateTime LastUpdate { get; set; } = DateTime.UtcNow;

        [JsonProperty("mode")]
        public string Mode { get; set; }
    }

    // ============================================================================
    // AVAILABLE PARAMETERS
    // ============================================================================

    public class AvailableParameter
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("paramType")]
        public GrasshopperParamType ParamType { get; set; }

        [JsonProperty("default", NullValueHandling = NullValueHandling.Ignore)]
        public object Default { get; set; }

        [JsonProperty("minimum", NullValueHandling = NullValueHandling.Ignore)]
        public double? Minimum { get; set; }

        [JsonProperty("maximum", NullValueHandling = NullValueHandling.Ignore)]
        public double? Maximum { get; set; }

        [JsonProperty("stepSize", NullValueHandling = NullValueHandling.Ignore)]
        public double? StepSize { get; set; }

        [JsonProperty("atLeast")]
        public int AtLeast { get; set; } = 1;

        [JsonProperty("atMost")]
        public int AtMost { get; set; } = int.MaxValue;

        [JsonProperty("treeAccess")]
        public bool TreeAccess { get; set; }
    }

    public class AvailableParameters
    {
        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        [JsonProperty("parameters")]
        public List<AvailableParameter> Parameters { get; set; } = new List<AvailableParameter>();
    }

    // ============================================================================
    // JSON CONVERTER FOR DISCRIMINATED UNION
    // ============================================================================

    /// <summary>
    /// Custom JSON converter for LayoutItemBase discriminated union
    /// </summary>
    public class LayoutItemConverter : JsonConverter<LayoutItemBase>
    {
        public override LayoutItemBase ReadJson(JsonReader reader, Type objectType, LayoutItemBase existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var type = jsonObject["type"]?.Value<string>();
            var widgetType = jsonObject["widgetType"]?.Value<string>();

            LayoutItemBase item = (type, widgetType) switch
            {
                ("input", "number") => new InputNumberLayoutItem(),
                ("input", "text") => new InputTextLayoutItem(),
                ("input", "dropdown") => new InputDropdownLayoutItem(),
                ("input", "checkbox") => new InputCheckboxLayoutItem(),
                ("output", "text") => new OutputTextLayoutItem(),
                ("output", "number") => new OutputNumberLayoutItem(),
                _ => throw new JsonSerializationException($"Unknown layout item type: {type}/{widgetType}")
            };

            serializer.Populate(jsonObject.CreateReader(), item);
            return item;
        }

        public override void WriteJson(JsonWriter writer, LayoutItemBase value, JsonSerializer serializer)
        {
            var jsonObject = JObject.FromObject(value, new JsonSerializer
            {
                NullValueHandling = NullValueHandling.Ignore,
                ContractResolver = serializer.ContractResolver
            });
            jsonObject.WriteTo(writer);
        }
    }
}
`;

// Ensure output directory exists
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, output);
console.log(`Generated C# types at: ${outputPath}`);
